Cars/Models/Brand.cs
namespace Cars.Models;
public class Brand
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public string? Place { get; set; }
    public int? CreationYear { get; set; }
}

Cars/Models/Model.cs
namespace Cars.Models;
public class Model
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public double? Price { get; set; }
    public int BrandId { get; set; }
}

Cars/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Cars.Models;
namespace Cars.Controllers;
public class HomeController : Controller
{
    private readonly List<Brand>? _brands;
    public HomeController()
    {
        _brands = new List<Brand>()
        {
            new Brand{Id = 1, Name = "Ferrari", Place="Maranello, Italy", CreationYear = 1939},
            new Brand{Id = 2, Name = "Nissan", Place = "Japan", CreationYear = 1933},
            new Brand{Id = 3, Name = "Toyota", Place = "Japan", CreationYear = 1937}
        };
    }
    public IActionResult Index()
    {
        return View(_brands);
    }
    public IActionResult Details(int? id)
    {
        if (id == null) return BadRequest();
        else
        {
            Brand? brand = _brands.Find(b => b.Id == id);
            if (brand == null) return NotFound();
            else return View(brand);
        }
    }
}

Cars/Controllers/ModelController.cs
using Microsoft.AspNetCore.Mvc;
using Cars.Models;
namespace Cars.Controllers;
public class ModelController : Controller
{
    private readonly List<Model>? _models;
    public ModelController()
    {
        _models = new List<Model>()
        {
            new Model {Id = 1, BrandId = 1, Name = "F40", Price = 1_500_000},
            new Model {Id = 2, BrandId = 1, Name = "F50", Price = 4_000_000},
            new Model {Id = 3, BrandId = 1, Name = "Enzo", Price = 3_200_000},
            new Model {Id = 4, BrandId = 1, Name = "LaFerrari", Price = 3_100_000},
            new Model {Id = 5, BrandId = 1, Name = "Roma SA", Price = 200_000},
            new Model {Id = 6, BrandId = 1, Name = "488", Price = 283_000},
            new Model {Id = 7, BrandId = 2, Name = "GT-R", Price = 121_000},
            new Model {Id = 8, BrandId = 2, Name = "R32", Price = 20_000},
            new Model {Id = 9, BrandId = 2, Name = "S13", Price = 20_000},
            new Model {Id = 10, BrandId = 2, Name = "Skyline 25GT", Price = 37_000},
            new Model {Id = 11, BrandId = 2, Name = "180SX", Price = 26_000},
            new Model {Id = 12, BrandId = 3, Name = "Supra MK4", Price = 100_000},
            new Model {Id = 13, BrandId = 3, Name = "Supra RZ", Price = 57_000},
            new Model {Id = 14, BrandId = 3, Name = "Sprinter Trueno 1988", Price = 11_000}
        };
    }
    public IActionResult Index(int? id)
    {
        if (id == null) return View(_models);
        else
        {
            List<Model>? BrandModels = _models.FindAll(m => m.BrandId == id);
            if (BrandModels == null) return NotFound();
            else return View(BrandModels);
        }
    }
    public IActionResult Details(int? id)
    {
        if (id == null) return BadRequest();
        else
        {
            Model model = _models.Find(m => m.Id == id);
            if (model == null) return NotFound();
            else return View(model);
        }
    }
}

Cars/Views/Home/Details.cshtml
@model Brand
<h1>@Model.Name Details</h1>
<ul>
    <li>Id: @Model.Id</li>
    <li>Name: @Model.Name</li>
    <li>Place: @Model.Place</li>
    <li>Creation Year: @Model.CreationYear</li>
    <li><a asp-controller="Model" asp-action="Index" asp-route-id="@Model.Id">View Models</a></li>
</ul>

Cars/Views/Home/Index.cshtml
@model List<Brand>
<ul>
    @foreach (Brand brand in Model)
    {
        <li><a asp-controller="Home" asp-action="Details" asp-route-id="@brand.Id">@brand.Name</a></li>
    }
</ul>

Cars/Views/Model/Details.cshtml
@model Model
<h1>@Model.Name Details</h1>
<ul>
    <li>Id: @Model.Id</li>
    <li>Name: @Model.Name</li>
    <li>Price: $@Model.Price</li>
    <li><a asp-controller="Home" asp-action="Details" asp-route-id="@Model.BrandId">Brand: @Model.BrandId</a></li>
</ul>

Cars/Views/Model/Index.cshtml
@model List<Model>
<ul>
    @foreach (Model m in Model)
    {
         <li><a asp-controller="Model" asp-action="Details" asp-route-id="@m.Id">@m.Name</a></li>
    }
</ul>

Cars/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
   <header style="background-color: #ca1016 !important; padding: 0 15%;" class="d-flex justify-content-between align-items-center">
        <nav class="d-flex justify-content-between align-items-center" style="width: 60%;">
            <h6 class="logo nav-brand">
                <a style="color: #ffffff;" class="navbar-brand" asp-controller="Home" asp-action="Index">TURBO.AZ</a>
            </h6>
            <a class="nav-link text-white d-inline-block" asp-controller="Model" asp-action="Index">Bütün modellər</a>
            <a class="nav-link text-white d-inline-block" href="#">Avtosalonlar</a>
            <a class="nav-link text-white d-inline-block" href="#">Ehtiyat hissələr və aksesuarlar</a>
        </nav>
        <p style="background-color: #7ed321; color: #ffffff; padding:10px; border-radius: 7px; display: flex; justify-content: space-between; align-items: center">
            <i class="fas fa-circle-plus me-1" style="color:#7ed321; background-color:#ffffff; padding:1px; border-radius:50%;"></i>Yeni elan
        </p>
    </header>
    <main class="container mt-5">
        @RenderBody()
    </main>
</body>
</html>